"""empty message

Revision ID: c331ec219ce2
Revises: None
Create Date: 2015-12-29 16:55:20.361001

"""

# revision identifiers, used by Alembic.
revision = 'c331ec219ce2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dir_num', sa.Column('last_update_by', sa.String(length=10), nullable=True))
    op.add_column('handset', sa.Column('last_update_by', sa.String(length=10), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('handset', 'last_update_by')
    op.drop_column('dir_num', 'last_update_by')
    ### end Alembic commands ###
